version: "1"
title: "Pour-over coffee"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  - id: 1
    label: "start"
  - id: 2
    label: "measure-12oz-water"
    full_str: "Measure 12 ounces of water in the liquid measuring cup"
    depends: [1]
  - id: 3
    label: "pour-water-kettle"
    full_str: "Pour the water from the liquid measuring cup into the electric kettle"
    depends: ["measure-12oz-water"]
  - id: 4
    label: "place-dipper-on-mug"
    full_str: "Place the dripper on top of a coffee mug"
    depends: [1]
  - id: 5
    label: "filter-fold-half"
    full_str: Take the coffee filter and fold it in half to create a semi-circle
    depends: [1]
  - id: 6
    label: "filter-fold-quarter"
    full_str: "Fold the filter in half again to create a quarter-circle"
    depends: [5]
  - id: 7
    label: "place-filter"
    full_str: "Place the folded filter into the dripper such that the the point of the quarter-circle rests in the center of the dripper"
    depends: [6]
  - id: 8
    label: "spread-filter"
    full_str: "Spread the filter open to create a cone inside the dripper"
    depends: [7]
  - id: 9
    label: "scale-turn-on"
    full_str: "Turn on the kitchen scale"
    depends: [1]
  - id: 10
    label: "place-bowl-on-scale"
    full_str: "Place a bowl on the scale"
    depends: [7]
  - id: 11
    label: "zero-scale"
    full_str: "Zero the scale"
    depends: [10]
  - id: 12
    label: "measure-coffee-beans"
    full_str: "Add coffee beans to the bowl until the scale reads 25 grams"
    depends: [11]
  - id: 13
    label: "pour-coffee-grinder"
    full_str: "Pour the measured coffee beans into the coffee grinder"
    depends: [12]
  - id: 14
    label: "grind-beans"
    full_str: "Grind the coffee beans by pressing and holding down on the black part of the lid"
    depends: [13]
  - id: 15
    label: "pour-beans-filter"
    full_str: "Transfer the grounds to the filter cone"
    depends: [8, 14]
  - id: 16
    label: "thermometer-turn-on"
    full_str: "Turn on the thermometer"
    depends: [1]
  - id: 17
    label: "thermometer-in-water"
    full_str: "Place the end of the thermometer into the water."
    depends: [16]
  - id: 18
    label: "check-thermometer"
    full_str: "Check the temperature displayed on the thermometer."
    depends: [17]
  - id: 19
    label: "pour-water-grounds-wet"
    full_str: "Pour a small amount of water over the grounds in order to wet the grounds. Wait about 30 seconds."
    depends: [15, 4, 18]
  - id: 20
    label: "pour-water-grounds-circular"
    full_str: "Slowly pour the rest of the water over the grounds in a circular motion. Do not overfill beyond the top of the paper filter"
    depends: [19]
  - id: 21
    label: "water-drain"
    full_str: "Allow the rest of the water in the dripper to drain"
    depends: [20]
  - id: 22
    label: "remove-dripper"
    full_str: "Remove the dripper from the cup"
    depends: [21]
  - id: 23
    label: "remove-grounds"
    full_str: "Remove the coffee grounds and paper filter from the dripper. "
    depends: [21]
  - id: 24
    label: "discard-grounds"
    full_str: "Discard the coffee grounds and paper filter"
    depends: [23]
  - id: 25
    label: "done"
    full_str: "done"
    depends: [22, 24]
