version: "1"
title: "Dessert Quesadilla"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  - id: 1
    label: "start"
  - id: 2
    label: "place-tortilla"
    full_str: "Place tortilla on cutting board"
    depends: [1]
  - id: 3
    label: "scoop-nutella"
    full_str: "Use the butter knife to scoop nutella from the jar"
    depends: [1]
  - id: 4
    label: "spread-nutella-tortilla"
    full_str: "Spread nutella onto tortilla, leaving ½ inch uncovered at the edges"
    depends: [2, 3]
  - id: 5
    label: "slice-banana"
    full_str: "Slice banana"
    depends: [1]
  - id: 6
    label: "top-banana-slices"
    full_str: "Top with banana slices."
    depends: [5, 4]
  - id: 7
    label: "sprinkle-cinnamon"
    full_str: "Sprinkle small amount of cinnamon onto tortilla"
    depends: [4]
  - id: 8
    label: "fold-tortilla-half"
    full_str: "Fold tortilla in half into semi-cirlce"
    depends: [7, 6]
  - id: 9
    label: "slice-tortilla-half"
    full_str: "Slice tortilla in half using butter knife to create two triangular wedges"
    depends: [8]
  - id: 10
    label: "place-tortilla-wedge"
    full_str: "Place tortilla wedge on the plate"
    depends: [9]
    repeat: 2
  - id: 11
    label: "done"
    full_str: "done"
    depends: [10]
