_BASE_: "/angel_workspace/angel_system/berkeley/configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: '/shared/niudt/detectron2_ori/detectron2/tools/output_base_important/model_final.pth'
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
#    NUM_CLASSES: 1203
    NUM_CLASSES: 42
    SCORE_THRESH_TEST: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (428,)
  MAX_SIZE_TRAIN: 760
  MIN_SIZE_TEST: 428
  MAX_SIZE_TEST: 760
DATASETS:
  TRAIN: ("COFFEE_UCB_train",)
  TEST: ("COFFEE_UCB_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
#SOLVER:
#  STEPS: (120000, 160000)
#  MAX_ITER: 180000  # 180000 * 16 / 100000 ~ 28.8 epochs
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001

OUTPUT_DIR: './PTG_DEMO/11-5/train_Alex'

SOLVER:
  TOTAL_IMAGE_NUMBER: 1040
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  STEPS: (34000, 41000)
  MAX_ITER: 64000 # 500 * 1 / 10 ~ 500 epochs
  CHECKPOINT_PERIOD: 1000
  EPOCH: 50

VISUALIZER:
  CAM: False
